name: Lint Code Base

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Run super linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSX: true
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
